# Catppuccin Latte Theme
# A light, warm pastel theme

# UI colors
background = "#eff1f5"
foreground = "#4c4f69"
border = "#acb0be"
border_focused = "#1e66f5"
title = "#dc8a78"
subtitle = "#6c6f85"

# Diff colors
added = "#40a02b"
removed = "#d20f39"
modified = "#fe640b"
context = "#9ca0b0"
header = "#04a5e5"

# Status colors
info = "#1e66f5"
warning = "#df8e1d"
error = "#d20f39"
success = "#40a02b"

# Selection colors
selection_bg = "#ccd0da"
selection_fg = "#4c4f69"
cursor = "#dc8a78"

# Navigation colors
nav_bg = "#e6e9ef"
nav_fg = "#5c5f77"
nav_active = "#8839ef"

# Sidebar colors
sidebar_bg = "#dce0e8"
sidebar_fg = "#6c6f85"
sidebar_selected = "#bcc0cc"

# Scrollbar
scrollbar = "#ccd0da"
scrollbar_thumb = "#acb0be"