# Gruvbox Light Theme
# A retro groove color scheme - light variant with official colors

# UI colors
background = "#fbf1c7"       # light0
foreground = "#3c3836"       # dark1
border = "#d5c4a1"           # light2
border_focused = "#d79921"   # neutral_yellow
title = "#cc241d"            # neutral_red
subtitle = "#665c54"         # dark3

# Diff colors
added = "#98971a"            # neutral_green
removed = "#cc241d"          # neutral_red
modified = "#d79921"         # neutral_yellow
context = "#928374"          # gray
header = "#458588"           # neutral_blue

# Status colors
info = "#458588"             # neutral_blue
warning = "#d79921"          # neutral_yellow
error = "#cc241d"            # neutral_red
success = "#98971a"          # neutral_green

# Selection colors
selection_bg = "#ebdbb2"     # light1
selection_fg = "#3c3836"     # dark1
cursor = "#d65d0e"           # neutral_orange

# Navigation colors
nav_bg = "#f9f5d7"           # light0_hard
nav_fg = "#504945"           # dark2
nav_active = "#b16286"       # neutral_purple

# Sidebar colors
sidebar_bg = "#f2e5bc"       # light0_soft
sidebar_fg = "#504945"       # dark2
sidebar_selected = "#d5c4a1" # light2

# Scrollbar
scrollbar = "#d5c4a1"        # light2
scrollbar_thumb = "#a89984"  # light4

# Search colors
search_match = "#d79921"     # neutral_yellow
search_current = "#b16286"   # neutral_purple