# Nord Theme
# An arctic, north-bluish clean and elegant theme

# UI colors
background = "#2e3440"
foreground = "#d8dee9"
border = "#4c566a"
border_focused = "#88c0d0"
title = "#8fbcbb"
subtitle = "#e5e9f0"

# Diff colors
added = "#a3be8c"
removed = "#bf616a"
modified = "#ebcb8b"
context = "#616e88"
header = "#88c0d0"

# Status colors
info = "#5e81ac"
warning = "#ebcb8b"
error = "#bf616a"
success = "#a3be8c"

# Selection colors
selection_bg = "#434c5e"
selection_fg = "#eceff4"
cursor = "#d8dee9"

# Navigation colors
nav_bg = "#2e3440"
nav_fg = "#d8dee9"
nav_active = "#b48ead"

# Sidebar colors
sidebar_bg = "#2e3440"
sidebar_fg = "#d8dee9"
sidebar_selected = "#3b4252"

# Scrollbar
scrollbar = "#434c5e"
scrollbar_thumb = "#4c566a"