# Solarized Dark Theme
# Precision colors for machines and people - official colors

# UI colors
background = "#002b36"       # base03
foreground = "#839496"       # base0
border = "#073642"           # base02
border_focused = "#268bd2"   # blue
title = "#cb4b16"            # orange
subtitle = "#586e75"         # base01

# Diff colors
added = "#859900"            # green
removed = "#dc322f"          # red
modified = "#b58900"         # yellow
context = "#586e75"          # base01
header = "#2aa198"           # cyan

# Status colors
info = "#268bd2"             # blue
warning = "#b58900"          # yellow
error = "#dc322f"            # red
success = "#859900"          # green

# Selection colors
selection_bg = "#073642"     # base02
selection_fg = "#93a1a1"     # base1
cursor = "#d33682"           # magenta

# Navigation colors
nav_bg = "#073642"           # base02 (darkened)
nav_fg = "#839496"           # base0
nav_active = "#6c71c4"       # violet

# Sidebar colors
sidebar_bg = "#073642"       # base02 (darkened)
sidebar_fg = "#657b83"       # base00
sidebar_selected = "#073642" # base02

# Scrollbar
scrollbar = "#073642"        # base02
scrollbar_thumb = "#586e75"  # base01

# Search colors
search_match = "#b58900"     # yellow
search_current = "#6c71c4"   # violet